package state

// state_model_test.go: testes para state_model.go (modelo JSON).
// Migrado de session_state_test.go em 2026-09-21 (Fase 3).
import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/matheusdutra/agent-sync/internal/event"
)

func newTestSessionState() SessionState {
	now := time.Date(2026, 9, 19, 12, 0, 0, 0, time.UTC)
	return SessionState{
		SchemaVersion: SessionStateSchemaVersion,
		Project: SessionProject{
			Name: "agent-sync",
			Root: "/tmp/agent-sync",
		},
		Git: SessionGit{
			Branch:             "feat/poc-session-state",
			Head:               "7cb4dff",
			WorkingTreeSummary: "limpo",
		},
		Session: SessionMeta{
			ID:        "sess-2026-09-19-poc",
			StartedAt: now,
			UpdatedAt: now,
		},
		Decisions: []SessionDecision{
			{
				ID:        "D-1",
				Title:     "JSON canônico, MD view",
				Rationale: "evita divergência entre 5 CLIs reinterpretando STATE.md",
				MadeAt:    now,
			},
		},
		// A-37 Etapa 2: NextActions/Blockers removidos do struct; fonte canonica
		// e Tasks/Issues. Fixture preserva semantica para validar NextAction()
		// (shim que le de Tasks legacy_kind=todo|delivery, model.go:430) e
		// round-trip.
		Tasks: []SessionTask{
			{ID: "T-1", Title: "PoC: round-trip JSON → MD", Status: "in_progress", LegacyKind: "todo", StartedAt: now},
			{ID: "T-2", Title: "Wire em main.go", Status: "pending", LegacyKind: "todo", StartedAt: now},
		},
		Issues: []SessionIssue{
			{ID: "I-1", Title: "aguardando lockfile design", Severity: "medium", LegacyKind: "blocker", Description: "aguardando lockfile design", DetectedAt: now},
		},
		OpenQuestions: []string{"open: lockfile em FS local vs IPC"},
	}
}

func TestSessionStateRoundTrip(t *testing.T) {
	root := t.TempDir()
	original := newTestSessionState()

	if err := WriteSessionState(root, original); err != nil {
		t.Fatalf("write: %v", err)
	}

	if _, err := os.Stat(statePath(root)); err != nil {
		t.Fatalf("state file missing: %v", err)
	}

	loaded, err := ReadSessionState(root)
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	if loaded.SchemaVersion != original.SchemaVersion {
		t.Errorf("schema_version mismatch: %q vs %q", loaded.SchemaVersion, original.SchemaVersion)
	}
	if loaded.Project.Name != original.Project.Name {
		t.Errorf("project.name mismatch: %q vs %q", loaded.Project.Name, original.Project.Name)
	}
	if len(loaded.Tasks) != len(original.Tasks) {
		t.Errorf("tasks length mismatch: %d vs %d", len(loaded.Tasks), len(original.Tasks))
	}
	if loaded.Session.UpdatedAt.IsZero() {
		t.Errorf("updated_at não foi setado no write")
	}
}

func TestSessionStateRenderStable(t *testing.T) {
	s := newTestSessionState()
	first := RenderStateMD(s)
	second := RenderStateMD(s)

	firstNoTime := stripRenderTimestamp(first)
	secondNoTime := stripRenderTimestamp(second)

	if firstNoTime != secondNoTime {
		t.Fatalf("render não-determinístico (ignorando timestamp):\n--first--\n%s\n--second--\n%s", firstNoTime, secondNoTime)
	}

	if !strings.Contains(first, "# STATE — agent-sync") {
		t.Errorf("render não contém header do projeto")
	}
	if !strings.Contains(first, "schema v"+s.SchemaVersion) {
		t.Errorf("render não cita schema version %q", s.SchemaVersion)
	}
	if !strings.Contains(first, "D-1") {
		t.Errorf("render perdeu IDs de decisions")
	}
	// A-37 Etapa 1 (caminho C): A-1 nao precisa mais aparecer no render de NextActions
	// — secao "## Proximas acoes" agora e apenas header + aviso D-48 (itens foram
	// movidos para ## Tarefas). Fixture em newTestSessionState() ainda cria A-1
	// para validar NextAction/findAction.
}

// TestSessionStateRenderContemHeaderAutoGenerated verifica que o render
// inclui o header "# AUTO-GENERATED — edite .agent-sync/session-state.json
// ..." exigido pela ADR-002 Decisão 1.
func TestSessionStateRenderContemHeaderAutoGenerated(t *testing.T) {
	s := newTestSessionState()
	out := RenderStateMD(s)
	want := "# AUTO-GENERATED — edite .agent-sync/session-state.json e rode 'agent-sync state render'"
	if !strings.Contains(out, want) {
		t.Errorf("render não contém header AUTO-GENERATED literal:\n%s", out)
	}
	if !strings.HasPrefix(out, want) {
		t.Errorf("header AUTO-GENERATED não é a primeira linha do render:\n%s", out)
	}
}

// TestSessionStateNextAction verifica o shim NextAction (model.go:430) que
// deriva SessionAction de s.Tasks com legacy_kind=todo|delivery. A fixture
// newTestSessionState() cria T-1 (in_progress) e T-2 (pending) — o shim
// deve devolver T-2.
func TestSessionStateNextAction(t *testing.T) {
	s := newTestSessionState()
	a, ok := NextAction(s)
	if !ok {
		t.Fatal("next action esperado, não encontrado")
	}
	if a.Status != "pending" {
		t.Errorf("esperava action pending, veio %q (id=%s)", a.Status, a.ID)
	}
	if a.ID != "T-2" {
		t.Errorf("esperava T-2, veio %s", a.ID)
	}
}

// TestSessionStateValidationErrors exercita as 4 regras ativas de validate()
// em model.go:160. A-37 Etapa 2 removeu os checagens cruzadas de NextActions/
// Blockers (ID duplicado, references cruzadas) — substituidos por checagens
// adicionais do modelo canonico Tasks/Issues: status fora do enum deve ser
// pego na pratica pelo schema jsonschema (nao pelo validate() Go), entao o
// sub-teste foca nas 4 regras que validate() ainda aplica.
func TestSessionStateValidationErrors(t *testing.T) {
	cases := []struct {
		name   string
		mutate func(*SessionState)
	}{
		{
			"schema_version errado",
			func(s *SessionState) { s.SchemaVersion = "9.9" },
		},
		{
			"project.name vazio",
			func(s *SessionState) { s.Project.Name = "" },
		},
		{
			"project.root vazio",
			func(s *SessionState) { s.Project.Root = "" },
		},
		{
			"session.id vazio",
			func(s *SessionState) { s.Session.ID = "" },
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s := newTestSessionState()
			tc.mutate(&s)
			if err := s.validate(); err == nil {
				t.Errorf("esperava erro de validação, veio nil")
			}
		})
	}
}

func TestSessionStateWriteRejectsInvalid(t *testing.T) {
	root := t.TempDir()
	s := newTestSessionState()
	s.SchemaVersion = "0.0"

	if err := WriteSessionState(root, s); err == nil {
		t.Fatal("esperava write recusar schema_version inválido")
	}

	if _, err := os.Stat(statePath(root)); err == nil {
		t.Errorf("arquivo não deveria ter sido escrito")
	}
}

func TestSessionStateWriteAtomicNoTmp(t *testing.T) {
	root := t.TempDir()
	s := newTestSessionState()
	if err := WriteSessionState(root, s); err != nil {
		t.Fatalf("write: %v", err)
	}

	tmp := statePath(root) + ".tmp"
	if _, err := os.Stat(tmp); !os.IsNotExist(err) {
		t.Errorf("temp file não deveria existir após rename: err=%v", err)
	}

	entries, err := os.ReadDir(filepath.Join(root, SessionStateDirName))
	if err != nil {
		t.Fatalf("readdir: %v", err)
	}
	if len(entries) != 2 {
		t.Errorf("esperava 2 entries no .agent-sync (session-state.json + session-event.jsonl do hook), veio %d: %v", len(entries), entries)
	}
	var sawState, sawEvent bool
	for _, e := range entries {
		if e.Name() == SessionStateFileName {
			sawState = true
		}
		if e.Name() == event.SessionEventFileName {
			sawEvent = true
		}
	}
	if !sawState {
		t.Error("session-state.json nao encontrada")
	}
	if !sawEvent {
		t.Error("session-event.jsonl deveria ter sido criada pelo hook")
	}
}

// TestSessionStateWriteAtomicNoTmpUnico verifica que o tmpfile segue o
// padrão ".tmp.<pid>.<nanoTimestamp>" e não deixa leftover após rename.
func TestSessionStateWriteAtomicNoTmpUnico(t *testing.T) {
	root := t.TempDir()
	s := newTestSessionState()
	if err := WriteSessionState(root, s); err != nil {
		t.Fatalf("write: %v", err)
	}
	entries, err := os.ReadDir(filepath.Join(root, SessionStateDirName))
	if err != nil {
		t.Fatalf("readdir: %v", err)
	}
	for _, e := range entries {
		if strings.Contains(e.Name(), ".tmp.") {
			t.Errorf("tmpfile leftover encontrado: %s", e.Name())
		}
	}
}

// TestSessionStateWriteConcurrentLockless verifica que dois writes paralelos
// sem o lock opcional (default) completam sem corromper o arquivo. Atomic
// rename + tmpfile único por PID+nanoTimestamp garantem que o último vence.
func TestSessionStateWriteConcurrentLockless(t *testing.T) {
	root := t.TempDir()
	t.Setenv(SessionStateLockEnvVar, "")

	const writers = 4
	errs := make(chan error, writers)
	for i := 0; i < writers; i++ {
		i := i
		go func() {
			s := newTestSessionState()
			s.Session.ID = "sess-concurrent-" + string(rune('A'+i))
			errs <- WriteSessionState(root, s)
		}()
	}
	for i := 0; i < writers; i++ {
		if err := <-errs; err != nil {
			t.Errorf("writer %d falhou: %v", i, err)
		}
	}

	loaded, err := ReadSessionState(root)
	if err != nil {
		t.Fatalf("read após writes concorrentes: %v", err)
	}
	if !strings.HasPrefix(loaded.Session.ID, "sess-concurrent-") {
		t.Errorf("ID não é de um dos writers concorrentes: %q", loaded.Session.ID)
	}
}

// TestAcquireSessionLockBlocksUntilReleased verifica o lock opcional
// (AGENT_SYNC_SESSION_LOCK=1). Goroutine A adquire e segura; B bloqueia
// até A liberar.
func TestAcquireSessionLockBlocksUntilReleased(t *testing.T) {
	root := t.TempDir()

	releaseA, err := acquireSessionLock(root)
	if err != nil {
		t.Fatalf("A acquire: %v", err)
	}

	if _, err := os.Stat(lockPath(root)); err != nil {
		t.Fatalf("lockfile não criado: %v", err)
	}

	bStarted := make(chan struct{})
	bDone := make(chan error, 1)
	go func() {
		close(bStarted)
		releaseB, err := acquireSessionLock(root)
		bDone <- err
		if releaseB != nil {
			releaseB()
		}
	}()

	<-bStarted
	select {
	case <-bDone:
		t.Fatal("B conseguiu lock enquanto A segurava — não bloqueou")
	case <-time.After(50 * time.Millisecond):
	}

	releaseA()

	select {
	case err := <-bDone:
		if err != nil {
			t.Errorf("B falhou após A liberar: %v", err)
		}
	case <-time.After(SessionStateLockTimeout):
		t.Fatal("B não conseguiu lock após A liberar dentro do timeout")
	}

	if _, err := os.Stat(lockPath(root)); !os.IsNotExist(err) {
		t.Errorf("lockfile não foi removido após release: err=%v", err)
	}
}

func stripRenderTimestamp(s string) string {
	lines := strings.Split(s, "\n")
	var kept []string
	for _, line := range lines {
		if strings.HasPrefix(line, "> Renderizado por") {
			continue
		}
		if strings.HasPrefix(line, "- Última atualização:") {
			continue
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "\n")
}
